name: Update OpenAPI

on:
  workflow_dispatch:
  schedule:
    - cron: "25 * * * *"

jobs:
  openapi-gen:
    name: Update ${{ matrix.package }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.package }}
      cancel-in-progress: true
    continue-on-error: true

    strategy:
      matrix:
        package:
          - vercel-api-js
          - netlify-api
          - zoom-api-js
          - keycloak-api
          - nuki-api-js

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build OpenAPI spec from PR
        run: pnpm generate --filter=${{ matrix.package }}

      - name: Format code
        run: pnpm check:fix

      - name: Analyze changes and create changeset
        run: pnpm tsx ./.github/workflows/scripts/changes.ts ${{ matrix.package }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - run: git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: "Update OpenAPI Spec"
          committer: "SferaDev <SferaDev@users.noreply.github.com>"
          title: "[OpenAPI] Spec updates for ${{ matrix.package }}"
          body: |
            This is an autogenerated PR to update the OpenAPI spec with the latest merged changes.

            Before merging these changes, please review the update and test it out.
          branch: openapi/${{ matrix.package }}
