name: Update Dependencies

on:
  schedule:
    - cron: "0 7 * * 1" # Every Monday at 7am UTC
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install new versions
        run: |
          # Clear old overrides before updating
          # package.json pnpm.overrides are used to avoid package versions with security vulnerabilities
          jq '.pnpm.overrides = {}' package.json > package.tmp && mv package.tmp package.json
          pnpm install --no-frozen-lockfile

          # Update dependencies
          pnpm update --recursive --latest

          # Patch vulnerabilities
          # adds package.json pnpm.overrides section to avoid package versions with security vulnerabilities
          pnpm audit --fix || true
          pnpm install --no-frozen-lockfile

          # Update biome config
          pnpm biome migrate --write

          # Fix formatting and linting issues
          pnpm check:fix

          # Commit changes
          git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: "Update dependencies"
          committer: "SferaDev Bot <sferadev@users.noreply.github.com>"
          title: "Update dependencies"
          body: |
            This is an autogenerated PR to update the dependencies!
          branch: update-dependencies-${{ github.run_id }}
